org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Dsun.net.spi.nameservice.nameservers=8.8.8.8 -Dsun.net.spi.nameservice.provider.1=dns,sun
android.useAndroidX=true
android.enableJetifier=true

# Solo compilar x86_64 para el emulador (build más rápido)
reactNativeArchitectures=x86_64

newArchEnabled=false
hermesEnabled=true

# Deshabilitar auto-download de JDK
org.gradle.java.installations.auto-download=false
